version: '3.1'

services:

  mongo:
    image: mongo
    command:
      - --auth
      - --bind_ip_all
    ports:
      - 27017:27017
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rxmsa
      MONGO_INITDB_ROOT_PASSWORD: rxmsa2022!!
      MONGO_INITDB_DATABASE: rxmsa

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rxmsa
      ME_CONFIG_MONGODB_ADMINPASSWORD: rxmsa2022!!
      ME_CONFIG_MONGODB_URL: mongodb://rxmsa:rxmsa2022!!@mongodb:27017/

#
#services:
#
#  mongo:
#    image: mongo
#    command:
#      - --auth
#      - --bind_ip_all
#    restart: always
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: test
#      MONGO_INITDB_ROOT_PASSWORD: test1234
#      MONGO_INITDB_DATABASE: test
#      MONGO_DB_USERNAME: aaa
#      MONGO_DB_PASSWORD: bbbb
#    volumes:
#      - ./data/mongodb:/data/db
#      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongo-express
#    ports:
#      - 1081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
#      ME_CONFIG_MONGODB_URL: mongodb://admin:1234@mongo:27017/

#services:
#
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/