server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default


---
spring:
  cloud:
    stream:
      bindings:
        inputSample-in-0:
          destination: learning-spring-boot-comments  #consoumer
          group: learning-spring-boot
        outputSample-out-0:
          destination: learning-spring-boot-comments  #publisher
          group: learning-spring-boot
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://rxmsaUser:rxmsa2022!!@127.0.0.1:27017/rxmsa


  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: rxmsa2022!!
    port: 5672

